---
title: "NYC Taxi"
author: "ZJ"
date: "8/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(disk.frame)
setup_disk.frame()
```

## Loading the data
```{r}
system.time(nyc.df <- csv_to_disk.frame(list.files("c:/data/nyc-taxi-data/",pattern="*.csv", full.names = T)))
```

```{r}
sapply(list.files("c:/data/nyc-taxi-data/",pattern="*.csv", full.names = T), function(x) {
  ncol(data.table::fread(x, nrows = 2))
})
```

```{r}
a = nyc.df[,uniqueN(Dispatching_base_num), keep=names(nyc.df)[1]]
a
```


```{r}
nyc.df = disk.frame("nyc.df")
head(nyc.df)
```
```{r}
library(magrittr)
library(lubridate)
system.time(nyc2.df <- nyc.df %>%
  map(function(chunk) {
    chunk[!is.na(Dispatching_base_number), Dispatching_base_num := Dispatching_base_number]
    chunk[, Dispatching_base_number:=NULL]
    chunk[, Pickup_DateTime := lubridate::as_datetime(Pickup_DateTime)]
    chunk[!is.na(Pickup_date), Pickup_DateTime := lubridate::as_datetime(Pickup_date)]
    chunk[,Pickup_date:=NULL]
    chunk
  }, outdir="nyc2.df", lazy = FALSE, overwrite = TRUE))
```
```{r}
head(nyc2.df)
```
```{r}
system.time(rechunk(nyc2.df, nchunks = nchunks(nyc.df), shardby = "Dispatching_base_num"))
```

```{r}
a = collect(nyc2.df)
```