# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hashstr2i <- function(x, ngrps, prime1 = 3L, prime2 = 11L, prime3 = 15L) {
    .Call('_disk_frame_hashstr2i', PACKAGE = 'disk.frame', x, ngrps, prime1, prime2, prime3)
}

